/*
 * Date: 20/08/2026
 * Name: Penglei Fan - Bella / Cole Zinda
 *
 * File Path: src/viewRegistry.ts
 * Function: Registers client page routes and their React components
 */

import type { ComponentType } from "react";
import type { ViewDefinition } from "./types/models";
import ProfileDetails from "./pages/courier/settings/ProfileDetails";
import UploadDish from "./pages/chef/dishes/UploadDish";
import ChefOrderList from "./pages/chef/orders/ChefOrderList";
import ChefProfileDetails from "./pages/chef/profile/ChefProfileDetails";
import ProfileOverview from "./pages/customer/profile/ProfileOverview";
import CustomerOrderHistory from "./pages/customer/orders/CustomerOrderHistory";
import { AuthPage } from "./components/content/AuthPage";
import { PaymentMethodsPage } from "./components/content/PaymentMethodsPage";
import { MembershipPage } from "./components/content/MembershipPage";
import { CheckoutPage } from "./components/content/CheckoutPage";

export interface RegisteredView extends ViewDefinition {
  component?: ComponentType;
}

// This single registry is used by both routing and the screen directory
export const views: RegisteredView[] = [
  {
    id: 1,
    route: "/screen/001-earningsoverview",
    componentName: "EarningsOverview",
    title: "Earnings Overview",
    role: "courier",
    group: "wallet",
    kind: "wallet",
  },
  {
    id: 2,
    route: "/screen/002-walletbalance",
    componentName: "WalletBalance",
    title: "Wallet Balance",
    role: "courier",
    group: "wallet",
    kind: "wallet",
  },
  {
    id: 3,
    route: "/screen/003-wallettransactions",
    componentName: "WalletTransactions",
    title: "Wallet Transactions",
    role: "courier",
    group: "wallet",
    kind: "wallet",
  },
  {
    id: 4,
    route: "/screen/004-withdrawalhistory",
    componentName: "WithdrawalHistory",
    title: "Withdrawal History",
    role: "courier",
    group: "wallet",
    kind: "wallet",
  },
  {
    id: 5,
    route: "/screen/005-withdrawalform",
    componentName: "WithdrawalForm",
    title: "Withdraw Funds",
    role: "courier",
    group: "wallet",
    kind: "form",
  },
  {
    id: 6,
    route: "/screen/006-withdrawalsuccess",
    componentName: "WithdrawalSuccess",
    title: "Withdrawal Successful",
    role: "courier",
    group: "wallet",
    kind: "status",
  },
  {
    id: 7,
    route: "/screen/007-deliverymap",
    componentName: "DeliveryMap",
    title: "Delivery Map",
    role: "courier",
    group: "courier-orders",
    kind: "map",
  },
  {
    id: 8,
    route: "/screen/008-deliveryroute",
    componentName: "DeliveryRoute",
    title: "Delivery Route",
    role: "courier",
    group: "courier-orders",
    kind: "map",
  },
  {
    id: 9,
    route: "/screen/009-bankcardlist",
    componentName: "BankCardList",
    title: "Bank Cards",
    role: "courier",
    group: "settings",
    kind: "settings",
  },
  {
    id: 10,
    route: "/screen/010-changeemail",
    componentName: "ChangeEmail",
    title: "Change Email",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 11,
    route: "/screen/011-about",
    componentName: "About",
    title: "About Food Journal",
    role: "courier",
    group: "settings",
    kind: "info",
  },
  {
    id: 12,
    route: "/screen/012-workcity",
    componentName: "WorkCity",
    title: "Work City",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 13,
    route: "/screen/013-feedback",
    componentName: "Feedback",
    title: "Feedback",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 14,
    route: "/screen/014-profiledetails",
    component: ProfileDetails,
    componentName: "ProfileDetails",
    title: "Profile Details",
    role: "courier",
    group: "settings",
    kind: "settings",
  },
  {
    id: 15,
    route: "/screen/015-changeavatar",
    componentName: "ChangeAvatar",
    title: "Change Avatar",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 16,
    route: "/screen/016-identitydocument",
    componentName: "IdentityDocument",
    title: "Identity Document",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 17,
    route: "/screen/017-phonenumber",
    componentName: "PhoneNumber",
    title: "Phone Number",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 18,
    route: "/screen/018-termsandrules",
    componentName: "TermsAndRules",
    title: "Terms and Rules",
    role: "courier",
    group: "settings",
    kind: "info",
  },
  {
    id: 19,
    route: "/screen/019-passwordrequirementserror",
    componentName: "PasswordRequirementsError",
    title: "Password Requirements",
    role: "courier",
    group: "settings",
    kind: "status",
  },
  {
    id: 20,
    route: "/screen/020-passwordchangesuccess",
    componentName: "PasswordChangeSuccess",
    title: "Password Updated",
    role: "courier",
    group: "settings",
    kind: "status",
  },
  {
    id: 21,
    route: "/screen/021-passworderror",
    componentName: "PasswordError",
    title: "Password Error",
    role: "courier",
    group: "settings",
    kind: "status",
  },
  {
    id: 22,
    route: "/screen/022-phonechangesuccess",
    componentName: "PhoneChangeSuccess",
    title: "Phone Number Updated",
    role: "courier",
    group: "settings",
    kind: "status",
  },
  {
    id: 23,
    route: "/screen/023-phonealreadybound",
    componentName: "PhoneAlreadyBound",
    title: "Phone Number Already Linked",
    role: "courier",
    group: "settings",
    kind: "status",
  },
  {
    id: 24,
    route: "/screen/024-addhealthcertificate",
    componentName: "AddHealthCertificate",
    title: "Add Health Certificate",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 25,
    route: "/screen/025-addidentitydocument",
    componentName: "AddIdentityDocument",
    title: "Add Identity Document",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 26,
    route: "/screen/026-addbankcard",
    componentName: "AddBankCard",
    title: "Add Bank Card",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 27,
    route: "/screen/027-emergencycontact",
    componentName: "EmergencyContact",
    title: "Emergency Contact",
    role: "courier",
    group: "settings",
    kind: "form",
  },
  {
    id: 28,
    route: "/screen/028-settingshome",
    componentName: "SettingsHome",
    title: "Settings",
    role: "courier",
    group: "settings",
    kind: "settings",
  },
  {
    id: 29,
    route: "/screen/029-settingsoverview",
    componentName: "SettingsOverview",
    title: "Account Settings",
    role: "courier",
    group: "settings",
    kind: "settings",
  },
  {
    id: 30,
    route: "/screen/030-laboragreement",
    componentName: "LaborAgreement",
    title: "Labor Agreement and Code of Conduct",
    role: "courier",
    group: "settings",
    kind: "info",
  },
  {
    id: 31,
    route: "/screen/031-walletpaymentagreement",
    componentName: "WalletPaymentAgreement",
    title: "Wallet Payment Service Agreement",
    role: "courier",
    group: "settings",
    kind: "info",
  },
  {
    id: 32,
    route: "/screen/032-bankcarderror",
    componentName: "BankCardError",
    title: "Bank Card Error",
    role: "courier",
    group: "settings",
    kind: "status",
  },
  {
    id: 33,
    route: "/screen/033-bankcardadded",
    componentName: "BankCardAdded",
    title: "Bank Card Added",
    role: "courier",
    group: "settings",
    kind: "status",
  },
  {
    id: 34,
    route: "/screen/034-healthcertificate",
    componentName: "HealthCertificate",
    title: "Health Certificate",
    role: "courier",
    group: "settings",
    kind: "settings",
  },
  {
    id: 35,
    route: "/screen/035-bankcarddetails",
    componentName: "BankCardDetails",
    title: "Bank Card Details",
    role: "courier",
    group: "settings",
    kind: "settings",
  },
  {
    id: 36,
    route: "/screen/036-courierbrand",
    componentName: "CourierBrand",
    title: "Food Journal Courier",
    role: "courier",
    group: "settings",
    kind: "info",
  },
  {
    id: 37,
    route: "/screen/037-chef-profile",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Profile",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 38,
    route: "/screen/038-chef-storefront",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Storefront",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 39,
    route: "/screen/039-chef-profile-details",
    component: ChefProfileDetails,
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Profile Details",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 40,
    route: "/screen/040-chef-availability",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Availability",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 41,
    route: "/screen/041-chef-service-area",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Service Area",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 42,
    route: "/screen/042-chef-notifications",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Notifications",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 43,
    route: "/screen/043-chef-account",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Account",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 44,
    route: "/screen/044-chef-security",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Security",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 45,
    route: "/screen/045-chef-payment-profile",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Payment Profile",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 46,
    route: "/screen/046-chef-verification",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Verification",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 47,
    route: "/screen/047-recommendeddish",
    componentName: "RecommendedDish",
    title: "Recommended Dish",
    role: "chef",
    group: "dishes",
    kind: "detail",
  },
  {
    id: 48,
    route: "/screen/048-dishsoupcreate",
    componentName: "DishSoupCreate",
    title: "Create Soup Dish",
    role: "chef",
    group: "dishes",
    kind: "form",
  },
  {
    id: 49,
    route: "/screen/049-dishsoupedit",
    componentName: "DishSoupEdit",
    title: "Edit Soup Dish",
    role: "chef",
    group: "dishes",
    kind: "form",
  },
  {
    id: 50,
    route: "/screen/050-dishsouppricing",
    componentName: "DishSoupPricing",
    title: "Edit Dish Pricing",
    role: "chef",
    group: "dishes",
    kind: "form",
  },
  {
    id: 51,
    route: "/screen/051-dishsoupavailability",
    componentName: "DishSoupAvailability",
    title: "Edit Dish Availability",
    role: "chef",
    group: "dishes",
    kind: "form",
  },
  {
    id: 52,
    route: "/screen/052-uploaddish",
    component: UploadDish,
    componentName: "UploadDish",
    title: "Upload Dish",
    role: "chef",
    group: "dishes",
    kind: "form",
  },
  {
    id: 53,
    route: "/screen/053-dishrecommendationhint",
    componentName: "DishRecommendationHint",
    title: "Recommendation Tip",
    role: "chef",
    group: "dishes",
    kind: "info",
  },
  {
    id: 54,
    route: "/screen/054-dishrecommendationsettings",
    componentName: "DishRecommendationSettings",
    title: "Recommendation Settings",
    role: "chef",
    group: "dishes",
    kind: "form",
  },
  {
    id: 55,
    route: "/screen/055-dishrecommendationrules",
    componentName: "DishRecommendationRules",
    title: "Recommendation Rules",
    role: "chef",
    group: "dishes",
    kind: "info",
  },
  {
    id: 56,
    route: "/screen/056-dishrecommendationconfirmation",
    componentName: "DishRecommendationConfirmation",
    title: "Recommendation Confirmation",
    role: "chef",
    group: "dishes",
    kind: "status",
  },
  {
    id: 57,
    route: "/screen/057-dishpreview",
    componentName: "DishPreview",
    title: "Dish Preview",
    role: "chef",
    group: "dishes",
    kind: "detail",
  },
  {
    id: 58,
    route: "/screen/058-dishpreviewupdated",
    componentName: "DishPreviewUpdated",
    title: "Updated Dish Preview",
    role: "chef",
    group: "dishes",
    kind: "detail",
  },
  {
    id: 59,
    route: "/screen/059-recipeeditorstepone",
    componentName: "RecipeEditorStepOne",
    title: "Recipe Editor — Step One",
    role: "chef",
    group: "recipes",
    kind: "form",
  },
  {
    id: 60,
    route: "/screen/060-recipeeditoroverview",
    componentName: "RecipeEditorOverview",
    title: "Recipe Editor Overview",
    role: "chef",
    group: "recipes",
    kind: "form",
  },
  {
    id: 61,
    route: "/screen/061-recipeeditoringredients",
    componentName: "RecipeEditorIngredients",
    title: "Recipe Ingredients",
    role: "chef",
    group: "recipes",
    kind: "form",
  },
  {
    id: 62,
    route: "/screen/062-recipeeditorinstructions",
    componentName: "RecipeEditorInstructions",
    title: "Recipe Instructions",
    role: "chef",
    group: "recipes",
    kind: "form",
  },
  {
    id: 63,
    route: "/screen/063-recipeeditornutrition",
    componentName: "RecipeEditorNutrition",
    title: "Recipe Nutrition",
    role: "chef",
    group: "recipes",
    kind: "form",
  },
  {
    id: 64,
    route: "/screen/064-recipeeditortags",
    componentName: "RecipeEditorTags",
    title: "Recipe Tags",
    role: "chef",
    group: "recipes",
    kind: "form",
  },
  {
    id: 65,
    route: "/screen/065-recipeeditorphotos",
    componentName: "RecipeEditorPhotos",
    title: "Recipe Photos",
    role: "chef",
    group: "recipes",
    kind: "form",
  },
  {
    id: 66,
    route: "/screen/066-recipeeditorpreview",
    componentName: "RecipeEditorPreview",
    title: "Recipe Editor Preview",
    role: "chef",
    group: "recipes",
    kind: "detail",
  },
  {
    id: 67,
    route: "/screen/067-recipepreview",
    componentName: "RecipePreview",
    title: "Recipe Preview",
    role: "chef",
    group: "recipes",
    kind: "detail",
  },
  {
    id: 68,
    route: "/screen/068-recipelibrary",
    componentName: "RecipeLibrary",
    title: "Recipe Library",
    role: "chef",
    group: "recipes",
    kind: "list",
  },
  {
    id: 69,
    route: "/screen/069-recipedelete",
    componentName: "RecipeDelete",
    title: "Delete Recipe",
    role: "chef",
    group: "recipes",
    kind: "status",
  },
  {
    id: 70,
    route: "/screen/070-cheforderhistoryempty",
    componentName: "ChefOrderHistoryEmpty",
    title: "Order History — Empty",
    role: "chef",
    group: "orders",
    kind: "empty",
  },
  {
    id: 71,
    route: "/screen/071-cheforderhistory",
    componentName: "ChefOrderHistory",
    title: "Order History",
    role: "chef",
    group: "orders",
    kind: "list",
  },
  {
    id: 72,
    route: "/screen/072-chefcancelorderother",
    componentName: "ChefCancelOrderOther",
    title: "Cancel Order — Other Reason",
    role: "chef",
    group: "orders",
    kind: "form",
  },
  {
    id: 73,
    route: "/screen/073-chefcancelorderprompt",
    componentName: "ChefCancelOrderPrompt",
    title: "Cancel Order Confirmation",
    role: "chef",
    group: "orders",
    kind: "status",
  },
  {
    id: 74,
    route: "/screen/074-chefcancelorderdetails",
    componentName: "ChefCancelOrderDetails",
    title: "Cancel Order Details",
    role: "chef",
    group: "orders",
    kind: "detail",
  },
  {
    id: 75,
    route: "/screen/075-chefordermap",
    componentName: "ChefOrderMap",
    title: "Order Map",
    role: "chef",
    group: "orders",
    kind: "map",
  },
  {
    id: 76,
    route: "/screen/076-chefcurrentorderdetailsupdated",
    componentName: "ChefCurrentOrderDetailsUpdated",
    title: "Current Order Details — Updated",
    role: "chef",
    group: "orders",
    kind: "detail",
  },
  {
    id: 77,
    route: "/screen/077-chefcurrentorderdetails",
    componentName: "ChefCurrentOrderDetails",
    title: "Current Order Details",
    role: "chef",
    group: "orders",
    kind: "detail",
  },
  {
    id: 78,
    route: "/screen/078-cheforderlistempty",
    componentName: "ChefOrderListEmpty",
    title: "Orders — Empty",
    role: "chef",
    group: "orders",
    kind: "empty",
  },
  {
    id: 79,
    route: "/screen/079-cheforderlisterror",
    componentName: "ChefOrderListError",
    title: "Orders — Error",
    role: "chef",
    group: "orders",
    kind: "error",
  },
  {
    id: 80,
    route: "/screen/080-cheforderlistupdated",
    componentName: "ChefOrderListUpdated",
    title: "Orders — Updated",
    role: "chef",
    group: "orders",
    kind: "list",
  },
  {
    id: 81,
    route: "/screen/081-cheforderlistpreparing",
    componentName: "ChefOrderListPreparing",
    title: "Orders — Preparing",
    role: "chef",
    group: "orders",
    kind: "list",
  },
  {
    id: 82,
    route: "/screen/082-cheforderlistready",
    componentName: "ChefOrderListReady",
    title: "Orders — Ready",
    role: "chef",
    group: "orders",
    kind: "list",
  },
  {
    id: 83,
    route: "/screen/083-cheforderlist",
    component: ChefOrderList,
    componentName: "ChefOrderList",
    title: "Orders",
    role: "chef",
    group: "orders",
    kind: "list",
  },
  {
    id: 84,
    route: "/screen/084-cheforderlistpagetwo",
    componentName: "ChefOrderListPageTwo",
    title: "Orders — Page Two",
    role: "chef",
    group: "orders",
    kind: "list",
  },
  {
    id: 85,
    route: "/screen/085-chef-public-information",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Public Information",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 86,
    route: "/screen/086-chef-store-hours",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Store Hours",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 87,
    route: "/screen/087-chef-delivery-settings",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Delivery Settings",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 88,
    route: "/screen/088-chef-payment-settings",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Payment Settings",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 89,
    route: "/screen/089-chef-support",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Support",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 90,
    route: "/screen/090-chef-privacy",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Privacy",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 91,
    route: "/screen/091-chef-account-verification",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Account Verification",
    role: "chef",
    group: "profile",
    kind: "settings",
  },
  {
    id: 92,
    route: "/screen/092-chef-payout-history",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Payout History",
    role: "chef",
    group: "profile",
    kind: "list",
  },
  {
    id: 93,
    route: "/screen/093-chef-business-address",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Business Address",
    role: "chef",
    group: "profile",
    kind: "form",
  },
  {
    id: 94,
    route: "/screen/094-chef-profile-preview",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Profile Preview",
    role: "chef",
    group: "profile",
    kind: "detail",
  },
  {
    id: 95,
    route: "/screen/095-chef-profile-saved",
    componentName: "ChefProfileView",
    sharedComponent: true,
    title: "Chef Profile Saved",
    role: "chef",
    group: "profile",
    kind: "status",
  },
  {
    id: 96,
    route: "/screen/096-profileoverview",
    component: ProfileOverview,
    componentName: "ProfileOverview",
    title: "Profile Overview",
    role: "customer",
    group: "profile",
    kind: "settings",
  },
  {
    id: 97,
    route: "/screen/097-profilefavorites",
    componentName: "ProfileFavorites",
    title: "Favorite Chefs",
    role: "customer",
    group: "profile",
    kind: "list",
  },
  {
    id: 98,
    route: "/screen/098-profileaddresses",
    componentName: "ProfileAddresses",
    title: "Saved Addresses",
    role: "customer",
    group: "profile",
    kind: "settings",
  },
  {
    id: 99,
    route: "/screen/099-profilepayment",
    componentName: "ProfilePayment",
    title: "Payment Methods",
    role: "customer",
    group: "profile",
    kind: "settings",
    component: PaymentMethodsPage,
  },
  {
    id: 100,
    route: "/screen/100-profilesecurity",
    componentName: "ProfileSecurity",
    title: "Account Security",
    role: "customer",
    group: "profile",
    kind: "settings",
  },
  {
    id: 101,
    route: "/screen/101-profilepreferences",
    componentName: "ProfilePreferences",
    title: "Food Preferences",
    role: "customer",
    group: "profile",
    kind: "settings",
  },
  {
    id: 102,
    route: "/screen/102-recipecomments",
    componentName: "RecipeComments",
    title: "Recipe Comments",
    role: "customer",
    group: "recipes",
    kind: "list",
  },
  {
    id: 103,
    route: "/screen/103-recipesteps",
    componentName: "RecipeSteps",
    title: "Recipe Steps",
    role: "customer",
    group: "recipes",
    kind: "detail",
  },
  {
    id: 104,
    route: "/screen/104-customerorderhistoryempty",
    componentName: "CustomerOrderHistoryEmpty",
    title: "Order History — Empty",
    role: "customer",
    group: "orders",
    kind: "empty",
  },
  {
    id: 105,
    route: "/screen/105-customerorderhistory",
    component: CustomerOrderHistory,
    componentName: "CustomerOrderHistory",
    title: "Order History",
    role: "customer",
    group: "orders",
    kind: "list",
  },
  {
    id: 106,
    route: "/screen/106-customercancelorderother",
    componentName: "CustomerCancelOrderOther",
    title: "Cancel Order — Other Reason",
    role: "customer",
    group: "orders",
    kind: "form",
  },
  {
    id: 107,
    route: "/screen/107-customercancelorder",
    componentName: "CustomerCancelOrder",
    title: "Cancel Order",
    role: "customer",
    group: "orders",
    kind: "status",
  },
  {
    id: 108,
    route: "/screen/108-customercancelorderdetails",
    componentName: "CustomerCancelOrderDetails",
    title: "Cancel Order Details",
    role: "customer",
    group: "orders",
    kind: "detail",
  },
  {
    id: 109,
    route: "/screen/109-customerordermap",
    componentName: "CustomerOrderMap",
    title: "Delivery Map",
    role: "customer",
    group: "orders",
    kind: "map",
  },
  {
    id: 110,
    route: "/screen/110-customercurrentorderupdated",
    componentName: "CustomerCurrentOrderUpdated",
    title: "Current Order — Updated",
    role: "customer",
    group: "orders",
    kind: "detail",
  },
  {
    id: 111,
    route: "/screen/111-customercurrentorderalternate",
    componentName: "CustomerCurrentOrderAlternate",
    title: "Current Order — Alternate View",
    role: "customer",
    group: "orders",
    kind: "detail",
  },
  {
    id: 112,
    route: "/screen/112-customercurrentorder",
    componentName: "CustomerCurrentOrder",
    title: "Current Order",
    role: "customer",
    group: "orders",
    kind: "detail",
  },
  {
    id: 113,
    route: "/screen/113-customerorderlistempty",
    componentName: "CustomerOrderListEmpty",
    title: "Orders — Empty",
    role: "customer",
    group: "orders",
    kind: "empty",
  },
  {
    id: 114,
    route: "/screen/114-customerorderlisterror",
    componentName: "CustomerOrderListError",
    title: "Orders — Error",
    role: "customer",
    group: "orders",
    kind: "error",
  },
  {
    id: 115,
    route: "/screen/115-customerorderlistupdated",
    componentName: "CustomerOrderListUpdated",
    title: "Orders — Updated",
    role: "customer",
    group: "orders",
    kind: "list",
  },
  {
    id: 116,
    route: "/screen/116-customerorderlist",
    componentName: "CustomerOrderList",
    title: "Orders",
    role: "customer",
    group: "orders",
    kind: "list",
  },
  {
    id: 117,
    route: "/screen/117-customerorderlistpagetwo",
    componentName: "CustomerOrderListPageTwo",
    title: "Orders — Page Two",
    role: "customer",
    group: "orders",
    kind: "list",
  },
  {
    id: 118,
    route: "/screen/118-paymentfailed",
    componentName: "PaymentFailed",
    title: "Payment Failed",
    role: "customer",
    group: "home",
    kind: "error",
  },
  {
    id: 119,
    route: "/screen/119-paymentsuccessful",
    componentName: "PaymentSuccessful",
    title: "Payment Successful",
    role: "customer",
    group: "home",
    kind: "status",
  },
  {
    id: 120,
    route: "/screen/120-customerdeliverymap",
    componentName: "CustomerDeliveryMap",
    title: "Delivery Map",
    role: "customer",
    group: "home",
    kind: "map",
  },
  {
    id: 121,
    route: "/screen/121-ordernote",
    componentName: "OrderNote",
    title: "Order Note",
    role: "customer",
    group: "home",
    kind: "form",
  },
  {
    id: 122,
    route: "/screen/122-addordernote",
    componentName: "AddOrderNote",
    title: "Add Order Note",
    role: "customer",
    group: "home",
    kind: "form",
  },
  {
    id: 123,
    route: "/screen/123-followedchef",
    componentName: "FollowedChef",
    title: "Following",
    role: "customer",
    group: "home",
    kind: "status",
  },
  {
    id: 124,
    route: "/screen/124-searchresults",
    componentName: "SearchResults",
    title: "Search Results",
    role: "customer",
    group: "home",
    kind: "list",
  },
  {
    id: 125,
    route: "/screen/125-paymentmethod",
    componentName: "PaymentMethod",
    title: "Payment Method",
    role: "customer",
    group: "home",
    kind: "settings",
    component: CheckoutPage,
  },
  {
    id: 126,
    route: "/screen/126-dishlist",
    componentName: "DishList",
    title: "Dish List",
    role: "customer",
    group: "home",
    kind: "list",
  },
  {
    id: 127,
    route: "/screen/127-dishlistempty",
    componentName: "DishListEmpty",
    title: "Dish List — Empty",
    role: "customer",
    group: "home",
    kind: "empty",
  },
  {
    id: 128,
    route: "/screen/128-dishreviews",
    componentName: "DishReviews",
    title: "Dish Reviews",
    role: "customer",
    group: "home",
    kind: "list",
  },
  {
    id: 129,
    route: "/screen/129-dishdetails",
    componentName: "DishDetails",
    title: "Dish Details",
    role: "customer",
    group: "home",
    kind: "detail",
  },
  {
    id: 130,
    route: "/screen/130-dishdetailsempty",
    componentName: "DishDetailsEmpty",
    title: "Dish Details — Unavailable",
    role: "customer",
    group: "home",
    kind: "empty",
  },
  {
    id: 131,
    route: "/screen/131-shoppingcart",
    componentName: "ShoppingCart",
    title: "Shopping Cart",
    role: "customer",
    group: "home",
    kind: "cart",
  },
  {
    id: 132,
    route: "/screen/132-selectdeliverytime",
    componentName: "SelectDeliveryTime",
    title: "Select Delivery Time",
    role: "customer",
    group: "home",
    kind: "form",
  },
  {
    id: 133,
    route: "/screen/133-deliveryaddress",
    componentName: "DeliveryAddress",
    title: "Delivery Address",
    role: "customer",
    group: "home",
    kind: "form",
  },
  {
    id: 134,
    route: "/screen/134-tableware",
    componentName: "Tableware",
    title: "Tableware Preferences",
    role: "customer",
    group: "home",
    kind: "form",
  },
  {
    id: 135,
    route: "/",
    componentName: "CustomerHome",
    title: "Home",
    role: "customer",
    group: "home",
    kind: "home",
  },
  {
    id: 136,
    route: "/screen/136-memberregistrationstepone",
    componentName: "MemberRegistrationStepOne",
    title: "Member Registration — Step One",
    role: "auth",
    group: "auth",
    kind: "form",
    component: AuthPage,
  },
  {
    id: 137,
    route: "/screen/137-memberregistrationsteptwo",
    componentName: "MemberRegistrationStepTwo",
    title: "Member Registration — Step Two",
    role: "auth",
    group: "auth",
    kind: "form",
    component: AuthPage,
  },
  {
    id: 138,
    route: "/screen/138-memberregistrationstepthree",
    componentName: "MemberRegistrationStepThree",
    title: "Member Registration — Step Three",
    role: "auth",
    group: "auth",
    kind: "form",
    component: AuthPage,
  },
  {
    id: 139,
    route: "/screen/139-coldstart",
    componentName: "ColdStart",
    title: "Welcome",
    role: "auth",
    group: "auth",
    kind: "info",
  },
  {
    id: 140,
    route: "/screen/140-promotion",
    componentName: "Promotion",
    title: "Promotion",
    role: "auth",
    group: "auth",
    kind: "detail",
  },
  {
    id: 141,
    route: "/screen/141-coldstartalternate",
    componentName: "ColdStartAlternate",
    title: "Welcome — Returning User",
    role: "auth",
    group: "auth",
    kind: "info",
  },
  {
    id: 142,
    route: "/screen/142-signin",
    componentName: "SignIn",
    title: "Sign In",
    role: "auth",
    group: "auth",
    kind: "form",
    component: AuthPage,
  },
  {
    id: 143,
    route: "/screen/143-messagecenter",
    componentName: "MessageCenter",
    title: "Messages",
    role: "courier",
    group: "messages",
    kind: "messages",
  },
  {
    id: 144,
    route: "/screen/144-messagethreadone",
    componentName: "MessageThreadOne",
    title: "Message Thread",
    role: "courier",
    group: "messages",
    kind: "messages",
  },
  {
    id: 145,
    route: "/screen/145-messagethreadtwo",
    componentName: "MessageThreadTwo",
    title: "Message Thread — Order Update",
    role: "courier",
    group: "messages",
    kind: "messages",
  },
  {
    id: 146,
    route: "/screen/146-messagethreadthree",
    componentName: "MessageThreadThree",
    title: "Message Thread — Support",
    role: "courier",
    group: "messages",
    kind: "messages",
  },
  {
    id: 147,
    route: "/screen/147-messagethreadfour",
    componentName: "MessageThreadFour",
    title: "Message Thread — Customer",
    role: "courier",
    group: "messages",
    kind: "messages",
  },
  {
    id: 148,
    route: "/screen/148-messagethreadfive",
    componentName: "MessageThreadFive",
    title: "Message Thread — Kitchen",
    role: "courier",
    group: "messages",
    kind: "messages",
  },
  {
    id: 149,
    route: "/screen/149-notification-center",
    componentName: "NotificationCenter",
    title: "Notifications",
    role: "courier",
    group: "messages",
    kind: "messages",
  },
  {
    id: 150,
    route: "/screen/150-membership",
    component: MembershipPage,
    componentName: "Membership",
    title: "Membership",
    role: "customer",
    group: "membership",
    kind: "info",
  },
];
